# WIP: This file is a work in progress and is not yet used by the application.
code-systems:
  - loinc:
    enabled: true
    version: "2.72"

  - snomed:
    enabled: true
    version: ""

  - icd10:
    enabled: true
    version: ""

  - icd10cm:
    enabled: true
    version: ""
