name: Deploy Docker Image to GHCR

on:
  workflow_dispatch:
    inputs:
      bump-version:
        type: choice
        required: true
        description: Bump version
        default: patch
        options:
          - patch
          - minor
          - major
          - none

jobs:
  bump-version:
    name: "Bump Image VERSION"
    if: inputs.bump-version != 'none'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Auto Bump
        run: ./scripts/bump-version.sh ${{inputs.bump-version}}
      - uses: stefanzweifel/git-auto-commit-action@v5
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build & Push Terminology Server Image"
        run: |
          ./scripts/build-and-tag-docker-image.sh
          docker push --all-tags ghcr.io/bonfhir/terminology-server
